import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Resto Week Bingo',
  description: 'Generated by Waveform Analytics',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // check the cookie to determine auth state (server-side)
  const cookieStore = cookies(); // access the cookies from the request headers
  const appSession = (await cookieStore).get('appSession'); // check the appSession cookie

  const isAuthenticated = !!appSession;

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=New+Amsterdam:wght@400&display=swap"
          rel="stylesheet"
        />
        <title>layout</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavBar isAuthenticated={isAuthenticated} />
        <main style={{ padding: '10px' }}>{children}</main>
        <footer>
          <p style={{ textAlign: 'center' }}>©{new Date().getFullYear()} Waveform Analytics</p>
        </footer>
      </body>
    </html>
  );
}
